import Head from "next/head";
import { client } from "../lib/apollo";
import { gql } from "@apollo/client";
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function HomePage({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Opinion Media
        </h1>

       
      </main>

      
    </div>
  )
}

export async function getStaticProps() {
  // Format your GraphQL query using backticks `` and prepend gql
  const GET_POSTS = gql`
    query AllPostsQuery {
      posts {
        nodes {
          title
          content
          date
          uri
        }
      }
    }
  `;
  // Here we make a call with the client and pass in our query string to the
  // configuration objects 'query' property
  const response = await client.query({
    query: GET_POSTS,
  });
  // Once we get the response back, we need to traverse it to pull out the
  // data we want to pass into the HomePage

  const posts = response?.data?.posts?.nodes;

  // const posts = await getAllPosts()

  return {
    props: {
      posts,
    },
  };
}
